---
kind: pipeline
name: default

services:
  - name: mongodb
    image: mongo

steps:
  - name: install
    image: node:16
    commands:
      - npm install
  - name: lint
    image: node:16
    commands:
      - npm run lint
    depends_on:
      - install
  - name: test
    image: node:16
    environment:
      DB_HOST: mongodb
    commands:
      - npm test
    depends_on:
      - install
      - lint
