language: node_js
node_js: '12'
cache: yarn
services: mongodb

env:
  global:
    - NODE_ENV=test

addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

install:
  - yarn install

script:
  - yarn test
  - bash sonar.sh

after_success: yarn coverage
