environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '14'
    - nodejs_version: '16'
services:
  - mongodb
cache:
  - node_modules
install:
  - npm install
build: off
test_script:
  - npm run test
version: '{build}'
