version: "3"
services:
    api:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "37017:27017"
        volumes:
            - bookstore-volume:/data/db
volumes:
    bookstore-volume: {}
