version: '3.7'

services:
  dev:
    image: node:12
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 8000:8000
    networks:
      - bookstore
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - bookstore-volume:/data/db
    networks:
      - bookstore

networks:
  bookstore:
volumes:
  bookstore-volume:
