db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: npm start
  volumes:
    - .:/books-store
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    PORT: 8000 # this is optional, allows express to use process.env.PORT instead of a raw 3000